import type { Metadata } from "next";
import { Geist, Geist_Mono , Tajawal } from "next/font/google";
import "./globals.css";
import { dir } from "console";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tajawal = Tajawal({
  variable: "--font-tajawal", 
  subsets: ["arabic", "latin"], 
  weight: ['200','300','400','500', '700', '800','900'],
  style: ['normal'],
  display: 'swap', // لتحسين تجربة المستخدم أثناء تحميل الخط
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir='rtl'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tajawal.variable}` }
      >
        {children}
      </body>
    </html>
  );
}
